name: test
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - '1.8'
          - '^1.10.0-beta2'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
      # Mesa install copied from https://github.com/microsoft/OpticSim.jl
      - name: Install Mesa (Windows only)
        if: runner.os == 'Windows'
        shell: cmd
        working-directory: ${{ steps.setup-julia.outputs.julia-bindir }}
        run: |
          curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/21.3.5/mesa3d-21.3.5-release-msvc.7z
          "C:\Program Files\7-Zip\7z.exe" x mesa.7z
          mklink opengl32.dll "x64\opengl32.dll"
          mklink libglapi.dll "x64\libglapi.dll"
      - name: Cache artifacts
        uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts 
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: julia -e "using Pkg; Pkg.status(); Pkg.Registry.add(RegistrySpec(url = \"https://github.com/barche/CxxWrapTestRegistry.git\"))"
      - uses: julia-actions/julia-buildpkg@latest
      - name: install-xfvb
        if: runner.os == 'Linux'
        run: sudo apt-get install xvfb libxkbcommon-x11-0
      - name: test-linux
        if: runner.os == 'Linux' && matrix.version != '1.6'
        run: xvfb-run --auto-servernum julia --color=yes --check-bounds=yes --project -e 'using Pkg; Pkg.test(coverage=true)'
        env:
          XDG_RUNTIME_DIR: /tmp/runtime-runner
      - name: test-win-mac
        if: runner.os != 'Linux'
        uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
        env:
          DISABLE_AMEND_COVERAGE_FROM_SRC: yes
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          fail_ci_if_error: false
      - uses: domluna/JuliaFormatter-action@master
        with:
          args: -v .
        continue-on-error: true
