name: test
on:
  - push

defaults:
  run:
    shell: bash

jobs:
  test:
    name: julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        arch:
          - x64
        include:
          - os: ubuntu-latest
            prefix: xvfb-run
          - os: windows-latest
            version: '1'
            arch: x86
          - os: macos-14
            arch: aarch64
            version: '1'
        exclude:
          - os: ubuntu-latest
            version: 1.6
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
        with:
          prefix: ${{ matrix.prefix }}
      - uses: julia-actions/julia-processcoverage@latest
        env:
          DISABLE_AMEND_COVERAGE_FROM_SRC: yes